// This file is generated by GoAdmin CLI adm.
package box

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "box_nft" => http://localhost:9033/admin/info/box_nft
//
// example end
var Generators = map[string]table.Generator{

	"box_nft": GetBoxNftTable,

	// generators end
}
